In [1]:
import numpy as np
from sklearn.preprocessing import normalize

In [2]:
A = np.array([[1,2,3,],
              [5,6,7,],
              [9,10,11],
              [13,14,15]])
A

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [3]:
A_norm, norms = normalize(A, axis=0, return_norm=True)
A_norm.round(2), norms

(array([[0.06, 0.11, 0.15],
        [0.3 , 0.33, 0.35],
        [0.54, 0.55, 0.55],
        [0.78, 0.76, 0.75]]),
 array([16.61324773, 18.33030278, 20.09975124]))

In [4]:
A_norm[:,0]*norms[0]

array([ 1.,  5.,  9., 13.])

In [6]:
A_denorm = []
for i in range(len(A)-1):
    A_denorm.append(A_norm[:,i]*norms[i])
A_denorm = np.array(A_denorm).T

In [7]:
np.array(A_denorm)

array([[ 1.,  2.,  3.],
       [ 5.,  6.,  7.],
       [ 9., 10., 11.],
       [13., 14., 15.]])

In [11]:
A.shape[-1]

3