## Class Notes

In [2]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2023-05-25 06:10:37.701879: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-25 06:10:37.780792: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-25 06:10:37.781907: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-25 06:10:39.294491: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


2.12.0


In [3]:
scalar = tf.constant(7)
scalar

2023-05-25 06:10:41.004517: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-05-25 06:10:41.005284: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1956] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
another_matrix = tf.constant([[10.,7,],
                              [3.,2.],
                              [8.,9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [11]:
tensor = tf.constant([[[1,2,3]]])
tensor

<tf.Tensor: shape=(1, 1, 3), dtype=int32, numpy=array([[[1, 2, 3]]], dtype=int32)>

In [12]:
tensor.ndim

3

In [13]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [16]:
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [5,2]])

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  2],
       [ 3,  4]], dtype=int32)>

In [17]:
tf.ones([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [18]:
tf.zeros([3,3,3])

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [19]:
A = np.arange(1,25)
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [20]:
A = tf.constant(A, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [21]:
A.ndim

3

In [22]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [23]:
2*3*4*5

120

In [24]:
rank_4_tensor.dtype, rank_4_tensor.ndim, rank_4_tensor.shape, rank_4_tensor.shape[0], rank_4_tensor.shape[-1], tf.size(rank_4_tensor).numpy()

(tf.float32, 4, TensorShape([2, 3, 4, 5]), 2, 5, 120)

In [25]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [26]:
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])

rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [27]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [28]:
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [29]:
tensor = tf.constant([[10,7],
                      [3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [30]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [31]:
tensor * 10, tf.multiply(tensor,10)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]], dtype=int32)>)

In [32]:
tensor - 10, tf.add(tensor, -10)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]], dtype=int32)>)

In [33]:
tensor / 2, tf.divide(tensor, 2)

(<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[5. , 3.5],
        [1.5, 2. ]])>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[5. , 3.5],
        [1.5, 2. ]])>)

In [34]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [35]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [36]:
A1 = tf.constant([[1,2,5],
                  [7,2,1],
                  [3,3,3]])
A2 = tf.constant([[3,5],
                  [6,7],
                  [1,8]])

tf.matmul(A1,A2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [37]:
A1 @ A2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [38]:
B = tf.constant([1,2.])
B.dtype

tf.float32

In [39]:
C = tf.constant([1,2])
C.dtype

tf.int32

In [40]:
D = tf.cast(B, dtype=tf.float16)
D


<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 2.], dtype=float16)>

In [41]:
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [42]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [43]:
E = tf.constant(np.random.randint(0,100, 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([65, 23, 45, 29, 82, 59, 46, 60, 77, 22, 45, 21, 83, 73, 66, 97, 99,
       89, 86, 59, 50, 33, 59, 41, 30, 23, 24, 69, 48, 38, 23, 61, 11, 66,
       88, 88, 55, 81, 88, 42, 13, 20, 11, 82, 40,  6, 52, 55, 28, 70])>

In [44]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [45]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=6>

In [46]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [47]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [48]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2621>

In [49]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=25.55237>

In [50]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=652.92365>

In [51]:
F = tf.random.uniform([50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.98645246, 0.8026147 , 0.64379585, 0.21752036, 0.6740328 ,
       0.00151932, 0.5686053 , 0.52925825, 0.6132442 , 0.5054766 ,
       0.13308132, 0.15047216, 0.8923489 , 0.51807535, 0.5251982 ,
       0.8541939 , 0.1853615 , 0.42185533, 0.01468289, 0.36963916,
       0.12192273, 0.5273558 , 0.08718944, 0.4706111 , 0.10413957,
       0.14090407, 0.6771283 , 0.6251068 , 0.6361271 , 0.27575195,
       0.8070278 , 0.37056112, 0.7410917 , 0.35795522, 0.8933526 ,
       0.08088481, 0.37904084, 0.7118317 , 0.14265645, 0.47555637,
       0.4648627 , 0.12672663, 0.16358864, 0.21623194, 0.2687949 ,
       0.3474629 , 0.7245122 , 0.06202805, 0.80787516, 0.52376616],
      dtype=float32)>

In [52]:
tf.argmax(F) # index

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [53]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.98645246>

In [54]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=5>

In [55]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0015193224>

In [56]:
G = tf.constant(tf.random.uniform([50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.15179396, 0.8135382 , 0.08904672, 0.28517175, 0.27960074,
           0.34819186, 0.5262877 , 0.01897049, 0.86589944, 0.54211926,
           0.67142546, 0.8470634 , 0.82842004, 0.6417284 , 0.27203608,
           0.21322477, 0.67729115, 0.02318716, 0.6502588 , 0.03439617,
           0.61747503, 0.29355526, 0.06538796, 0.268569  , 0.66610456,
           0.03512299, 0.11866367, 0.00933385, 0.51478744, 0.8327353 ,
           0.69288945, 0.7871262 , 0.85071766, 0.5578188 , 0.7801784 ,
           0.15803897, 0.2555821 , 0.33972943, 0.90536726, 0.88021874,
           0.42193484, 0.15937638, 0.35667408, 0.88703465, 0.2715006 ,
           0.9435257 , 0.25470722, 0.5150883 , 0.946069  , 0.1300416 ]]]]],
      dtype=float32)>

In [57]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.15179396, 0.8135382 , 0.08904672, 0.28517175, 0.27960074,
       0.34819186, 0.5262877 , 0.01897049, 0.86589944, 0.54211926,
       0.67142546, 0.8470634 , 0.82842004, 0.6417284 , 0.27203608,
       0.21322477, 0.67729115, 0.02318716, 0.6502588 , 0.03439617,
       0.61747503, 0.29355526, 0.06538796, 0.268569  , 0.66610456,
       0.03512299, 0.11866367, 0.00933385, 0.51478744, 0.8327353 ,
       0.69288945, 0.7871262 , 0.85071766, 0.5578188 , 0.7801784 ,
       0.15803897, 0.2555821 , 0.33972943, 0.90536726, 0.88021874,
       0.42193484, 0.15937638, 0.35667408, 0.88703465, 0.2715006 ,
       0.9435257 , 0.25470722, 0.5150883 , 0.946069  , 0.1300416 ],
      dtype=float32)>

In [58]:
some_list = [0,1,2,3]

tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [60]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

## Exercises

In [71]:
# 1
x = tf.constant(1)
y = tf.constant([1,2])
A = tf.constant([[1,2],
                 [3,4]])
B = tf.constant([[[1,2,3]]])
x,y,A,B

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(1, 1, 3), dtype=int32, numpy=array([[[1, 2, 3]]], dtype=int32)>)

In [73]:
# 3
A = tf.random.uniform(shape=(5,300))
B = tf.random.uniform(shape=(5,300))
A,B

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.16335738, 0.59199536, 0.8516946 , ..., 0.85067093, 0.52638686,
         0.9038192 ],
        [0.11971354, 0.12814689, 0.64742184, ..., 0.5904455 , 0.46501172,
         0.09895682],
        [0.7709359 , 0.74733305, 0.5088414 , ..., 0.977051  , 0.16843009,
         0.33530986],
        [0.8251699 , 0.15559328, 0.8796953 , ..., 0.9915842 , 0.23578787,
         0.2807263 ],
        [0.24246311, 0.21274722, 0.5286895 , ..., 0.753791  , 0.998762  ,
         0.70588946]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.4055146 , 0.18717372, 0.0299654 , ..., 0.8768023 , 0.23256636,
         0.44992995],
        [0.10217452, 0.63725793, 0.3645202 , ..., 0.25892115, 0.8977351 ,
         0.48402047],
        [0.29817402, 0.92908704, 0.7023208 , ..., 0.25434732, 0.61014795,
         0.4036157 ],
        [0.9423368 , 0.9995794 , 0.2402699 , ..., 0.14439964, 0.23052621,
         0.30144286],
        [0.52473

In [75]:
# 4
tf.matmul(A,tf.transpose(B))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.20682 , 78.060074, 69.86621 , 74.794876, 78.29824 ],
       [72.26962 , 79.53987 , 69.57124 , 72.64743 , 73.74693 ],
       [74.84293 , 79.62022 , 72.364075, 78.06177 , 82.997116],
       [77.65066 , 79.353745, 74.18196 , 78.223885, 78.43384 ],
       [75.9274  , 78.55144 , 75.89819 , 78.51947 , 78.20623 ]],
      dtype=float32)>

In [81]:
tf.tensordot(A, A, axes=0)

<tf.Tensor: shape=(5, 300, 5, 300), dtype=float32, numpy=
array([[[[0.02668563, 0.09670681, 0.13913059, ..., 0.13896337,
          0.08598918, 0.14764553],
         [0.01955609, 0.02093374, 0.10576113, ..., 0.09645363,
          0.07596309, 0.01616533],
         [0.12593807, 0.12208237, 0.083123  , ..., 0.1596085 ,
          0.0275143 , 0.05477534],
         [0.13479759, 0.02541731, 0.14370471, ..., 0.1619826 ,
          0.03851769, 0.04585871],
         [0.03960814, 0.03475383, 0.08636533, ..., 0.12313732,
          0.16315514, 0.11531225]],

        [[0.09670681, 0.3504585 , 0.50419927, ..., 0.50359327,
          0.31161857, 0.53505677],
         [0.07086986, 0.07586236, 0.3832707 , ..., 0.349541  ,
          0.27528477, 0.05858198],
         [0.45639047, 0.4424177 , 0.30123174, ..., 0.5784097 ,
          0.09970983, 0.19850188],
         [0.48849675, 0.0921105 , 0.52077556, ..., 0.58701324,
          0.13958533, 0.16618867],
         [0.14353703, 0.12594536, 0.31298172, ..., 0.44624

In [82]:
# 6
A = tf.random.uniform(shape=(224,224,3))
A

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.54037714, 0.95120025, 0.95399   ],
        [0.6467757 , 0.48521233, 0.64364755],
        [0.27196133, 0.84357405, 0.5411366 ],
        ...,
        [0.9613178 , 0.47182584, 0.87803376],
        [0.04718602, 0.20706773, 0.00316632],
        [0.4804598 , 0.8646816 , 0.0931716 ]],

       [[0.9438642 , 0.03180563, 0.62332964],
        [0.13434994, 0.8573054 , 0.77857697],
        [0.1116327 , 0.95606995, 0.3790021 ],
        ...,
        [0.7250663 , 0.11856782, 0.09808278],
        [0.08598197, 0.68951154, 0.37495434],
        [0.8401302 , 0.08692443, 0.747406  ]],

       [[0.90810657, 0.5486295 , 0.90293133],
        [0.86452544, 0.74577296, 0.39832163],
        [0.3070612 , 0.61025715, 0.25765598],
        ...,
        [0.24572694, 0.17337883, 0.23270547],
        [0.9823624 , 0.41343737, 0.00487185],
        [0.5514375 , 0.7449944 , 0.6183759 ]],

       ...,

       [[0.0094465 , 0.08500791, 0.7482455 ],
        [0.97

In [84]:
# 7
tf.reduce_min(A), tf.reduce_max(A)

(<tf.Tensor: shape=(), dtype=float32, numpy=5.9604645e-07>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.99999917>)

In [85]:
# 8
A = tf.random.uniform(shape=(1,224,224,3))
B = tf.squeeze(A,axis=0)
A,B


(<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
 array([[[[0.8581666 , 0.44649184, 0.9317241 ],
          [0.02510226, 0.6485437 , 0.13660705],
          [0.94095397, 0.3847338 , 0.8646208 ],
          ...,
          [0.09569287, 0.9931985 , 0.17487276],
          [0.21844053, 0.7054652 , 0.79532564],
          [0.36999834, 0.6441492 , 0.11775267]],
 
         [[0.69922435, 0.5801791 , 0.87869227],
          [0.02418411, 0.42442822, 0.8696997 ],
          [0.6419182 , 0.6303208 , 0.58338773],
          ...,
          [0.6997907 , 0.91809034, 0.50157106],
          [0.6423228 , 0.10376549, 0.5488192 ],
          [0.9604647 , 0.19490612, 0.94285274]],
 
         [[0.06515884, 0.61697805, 0.26114023],
          [0.81418455, 0.6559005 , 0.6128646 ],
          [0.3859161 , 0.70112085, 0.64312506],
          ...,
          [0.32510233, 0.24205446, 0.5802387 ],
          [0.20863402, 0.70431554, 0.22972405],
          [0.9870937 , 0.8736162 , 0.8985667 ]],
 
         ...,
 
       

In [87]:
# 9
A = tf.random.uniform(shape=[10])
print(A)
tf.argmax(A), A[tf.argmax(A)]

tf.Tensor(
[0.1979078  0.53682876 0.77903605 0.42222726 0.43294215 0.64012706
 0.26359963 0.02488887 0.04056084 0.2947656 ], shape=(10,), dtype=float32)


(<tf.Tensor: shape=(), dtype=int64, numpy=2>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.77903605>)

In [92]:
# 10
A = tf.one_hot(tf.cast(A, dtype=tf.int32), depth=10)
A

<tf.Tensor: shape=(10, 10, 10), dtype=float32, numpy=
array([[[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0.,